spring:
  application:
    name: poc-api


  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://172.17.0.2:5432/postgres}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secreta}

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    default-property-inclusion: NON_NULL

  flyway:
    enabled: false

logging:
  level:
    root: ${LOG_LEVEL:error}
   # "[br.com.integra.poc.api]": trace
   # '[org.springframework.web.client]': ${LOG_LEVEL:trace} 
   #  '[org.hibernate.validator]': ${LOG_LEVEL:trace}
   #  '[org.hibernate.SQL]': ${LOG_LEVEL:trace}
   #  '[org.hibernate.type.descriptor.sql]': ${LOG_LEVEL:trace}
   # '[org.springframework.web]': ${LOG_LEVEL:trace}
   # '[reactor.netty.http.client]': ${LOG_LEVEL:trace}
 
server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}

management:
  server:
    port: ${MANAGEMENT_PORT:8081}
  endpoint:
    health:
      show-details: never
  endpoints:
    web.base-path: /

kafka:
   bootstrapServers: 172.17.0.3:9092
   topic: test-topic		
cors:
   origins: http://localhost:8100
   