
CREATE TABLE TB_LOGS (
    ID_EVT        BIGINT NOT NULL ,
    DT_INCLUSAO   TIMESTAMP WITH TIME ZONE,
    ST_RETORNO    SMALLINT,
    DT_ENVIO      TIMESTAMP WITH TIME ZONE,
    ST_ENVIO      SMALLINT,
    TX_BODY       TEXT
);

ALTER TABLE TB_LOGS ADD CONSTRAINT TB_LOGS_PK PRIMARY KEY ( ID_EVT );

CREATE SEQUENCE SQ_LOGS START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;